# -*- restclient -*-

# GET todos
GET http://localhost:8080/api/todos

# POST todo
POST http://localhost:8080/api/todo
Content-Type: application/json

{ "body": "This is the first TODO"}

# POST another todo
POST http://localhost:8080/api/todo
Content-Type: application/json

{ "body": "This is the second TODO"}

# POST yet another todo
POST http://localhost:8080/api/todo
Content-Type: application/json

{ "body": "This is the third TODO"}

# DELETE todo
DELETE http://localhost:8080/api/todo
Content-Type: application/json

{"id": 1}

# Update a todo
PUT http://localhost:8080/api/todo
Content-Type: application/json

{"id": 3, "body": "This is the edited third todo"}
